rvm:
  - 2.6
  - 2.7
addons:
  apt:
    packages:
      - postgresql-server-dev-9.6
  postgresql: 9.6
services:
  - posgresql
  - mysql
before_script:
  - mysql -e "create database lokka_test;"
  - psql -c "create database lokka_test;" -U postgres
env:
  - DATABASE_URL="mysql://0.0.0.0/lokka_test"
  - DATABASE_URL="postgres://postgres@127.0.0.1/lokka_test"
  - DUMMY=DUMMY # sqlite
